### ISSUE TITLE
ModuleNotFoundError: No module named 'adminapp'

### ISSUE THREAD

**Issue by BenzenBaws** [os2datascanner/os2datascanner#25]
Hello there!

Sorry for the amateur question - I've been trying to install the data scanner directly on a Ubuntu 18 VM while following your documentation on readthedocs.

Whenever I run the production_deploy.sh everything goes smoothly until the ** admin module ** part.

`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/OS2Production/src/os2datascanner/projects/admin/manage.py", line 13, in <module>
Create new password for superuser (os2)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/OS2Production/src/os2datascanner/projects/admin/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/var/OS2Production/python-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/OS2Production/python-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/var/OS2Production/python-env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/OS2Production/python-env/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/OS2Production/python-env/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'adminapp'
`

Cheers!

**Comment by dals83** [comment]
Hi @BenzenBaws,

Thank you for your question. 
It is completely our fault that you cannot get it running. production_deploy.sh is not supposed to be used any more. Instead you should be able to start everything by running docker-compose up -d after git cloning the repo.
Everything you need to know to get started should be available in the [README](https://github.com/os2datascanner/os2datascanner/blob/master/README.rst) file.

**Comment by BenzenBaws** [comment]
Hey @dals83 

Thank you for the quick answer!


The reason I wanted raw installation was because I have no knowledge about docker to be completely honest with you.

So a quick yes/no question if you'd be so kind - With Docker, is it possible to run/host the scanner so it is accessible internally on hostname/ip other than localhost?

No matter what I'll go find the proper documentation for Docker.
Once again, thank you so much!
