### ISSUE TITLE
Admin app + collector && Report app + collector crashes with exit code 1 on startup.

### ISSUE THREAD

**Issue by BenzenBaws** [os2datascanner/os2datascanner#28]
Hey again,

I'm having a lot of issues with docker-compose on an Ubuntu 18 server by following the documentation in the readme file.

docker-compose up -d results in admin&report_collector crashes with exit code 1 followed by the admin&report application.

I've followed the docker documentation and everything is up-to-date.

Any clues?

**Comment by dals83** [comment]
Hi @BenzenBaws,

Can you provide me with some more information. If you run docker-compose up --build admin_collector what do you see?

**Comment by BenzenBaws** [comment]
Sure! Actually I got it to work, but now whenever I try to create an organization I get the following error copied from the report_collector_1 container log(still exit code 1 with docker-compose ps):

`
2021-07-06T10:38:44.981576240Z Created channel=1

2021-07-06T10:40:16.973399238Z Stop

2021-07-06T10:40:16.974894121Z Closing connection (200): Normal shutdown

2021-07-06T10:40:16.975731712Z Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f33ed3aad30> params=<URLParameters host=queue port=5672 virtual_host=/ ssl=False>>>

2021-07-06T10:40:16.978500300Z Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f33ed3aad30> params=<URLParameters host=queue port=5672 virtual_host=/ ssl=False>>>

2021-07-06T10:40:16.979690832Z Closing connection (200): 'Normal shutdown'

2021-07-06T10:40:16.982046624Z Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.19.0.9', 33642), raddr=('172.19.0.4', 5672)>

2021-07-06T10:40:16.985697031Z _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.19.0.9', 33642), raddr=('172.19.0.4', 5672)>

2021-07-06T10:40:16.986419385Z Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.19.0.9', 33642), raddr=('172.19.0.4', 5672)>

2021-07-06T10:40:16.987486824Z AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'

2021-07-06T10:40:16.996525865Z Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'

2021-07-06T10:40:16.998820636Z Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.19.0.9', 33642), raddr=('172.19.0.4', 5672)>

2021-07-06T10:40:17.001922144Z User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<URLParameters host=queue port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')

2021-07-06T10:40:17.002573873Z Traceback (most recent call last):

2021-07-06T10:40:17.002710575Z   File "manage.py", line 23, in <module>

2021-07-06T10:40:17.003153614Z     execute_from_command_line(sys.argv)

2021-07-06T10:40:17.003297014Z   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

2021-07-06T10:40:17.003914700Z     utility.execute()

2021-07-06T10:40:17.004058080Z   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute

2021-07-06T10:40:17.004618822Z     self.fetch_command(subcommand).run_from_argv(self.argv)

2021-07-06T10:40:17.004760087Z   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv

2021-07-06T10:40:17.005294976Z     self.execute(*args, **cmd_options)

2021-07-06T10:40:17.005435132Z   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute

2021-07-06T10:40:17.006015952Z     output = self.handle(*args, **options)

2021-07-06T10:40:17.006140640Z   File "/code/src/os2datascanner/projects/report/reportapp/management/commands/pipeline_collector.py", line 275, in handle

2021-07-06T10:40:17.006704766Z     runner.run_consumer(exclusive=True)

2021-07-06T10:40:17.006721936Z   File "/code/src/os2datascanner/engine2/pipeline/utilities/pika.py", line 172, in run_consumer

2021-07-06T10:40:17.007261644Z     self.channel.start_consuming()

2021-07-06T10:40:17.007447521Z   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming

2021-07-06T10:40:17.008859324Z     self._process_data_events(time_limit=None)

2021-07-06T10:40:17.009042804Z   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events

2021-07-06T10:40:17.010403454Z     self.connection.process_data_events(time_limit=time_limit)

2021-07-06T10:40:17.010592334Z   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 834, in process_data_events

2021-07-06T10:40:17.011504315Z     self._dispatch_channel_events()

2021-07-06T10:40:17.011525823Z   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 566, in _dispatch_channel_events

2021-07-06T10:40:17.012165127Z     impl_channel._get_cookie()._dispatch_events()

2021-07-06T10:40:17.012305844Z   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1494, in _dispatch_events

2021-07-06T10:40:17.013481055Z     evt.properties, evt.body)

2021-07-06T10:40:17.013500210Z   File "/code/src/os2datascanner/engine2/pipeline/utilities/pika.py", line 155, in _queue_callback

2021-07-06T10:40:17.014000956Z     decoded_body, channel=method.routing_key):

2021-07-06T10:40:17.014171952Z   File "/code/src/os2datascanner/projects/report/reportapp/management/commands/pipeline_collector.py", line 65, in event_message_received_raw

2021-07-06T10:40:17.014518882Z     handle_event(event_type, instance, Organization)

2021-07-06T10:40:17.014681655Z   File "/code/src/os2datascanner/projects/report/reportapp/management/commands/pipeline_collector.py", line 226, in handle_event

2021-07-06T10:40:17.015210243Z     event_obj = cls.from_json_object(instance)

2021-07-06T10:40:17.015330260Z   File "/code/src/os2datascanner/projects/report/reportapp/models/organization_model.py", line 26, in from_json_object

2021-07-06T10:40:17.015706628Z     name=obj["name"],

2021-07-06T10:40:17.016026090Z TypeError: string indices must be integers

`

**Comment by BenzenBaws** [comment]
And the error also happens if I just simply update the existing OS2Datascanner organization

**Comment by BenzenBaws** [comment]
![image](https://user-images.githubusercontent.com/38756267/124589533-6356fc00-de5a-11eb-8a72-ee5b2d45993e.png)

**Comment by dals83** [comment]
Hi @BenzenBaws 
I have re-created the error and will try to fix it as fast as possible.
Thank you very much for reporting this.

**Comment by dals83** [comment]
New changes have been added to master.
@BenzenBaws can you verify that the reported bug is fixed now?

**Comment by BenzenBaws** [comment]
Hey @dals83
It is indeed fixed 👍
